name: creative
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  http: ^0.13.4
  shared_preferences: ^2.0.13
  google_maps_flutter: ^2.1.10
  geolocator: ^8.2.0
  geolocator_web: ^2.1.4
  geocoding: ^2.0.4
  url_launcher: ^6.1.0
  url_launcher_web: ^2.0.9
  flutter_easyloading: ^3.0.3
  age_calculator: ^1.0.0
  image_picker: ^0.8.5+3
  numberpicker: ^2.1.1
  location: ^4.4.0
  qrscan: ^0.3.3
  path_provider: ^2.0.11
  flutter_dotenv: ^5.0.2
  animated_splash_screen: ^1.3.0
  internet_connection_checker: ^0.0.1+3
  flutter_spinbox: ^0.10.0
  material_design_icons_flutter: 5.0.6996
  flutter_rating_bar: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/json/thai_amphures.json
    - assets/json/thai_provinces.json
    - assets/json/thai_tambons.json
    - assets/images/profile.png
    - assets/images/LGapp.png
    - assets/images/LogoApp.png
